server:
  port: 8888

spring:
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  profiles:
    group:
      dev: profile1
      prod: profile2
---
spring:
  config:
    activate:
      on-profile: profile1

api:
  url: http://localhost:7777

---
spring:
  config:
    activate:
      on-profile: profile2
